# -*- coding: utf-8 -*-
"""Assignments Week 13 - 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WbzX3o6ZXGf9itZJlQ2JF4VPp1f6EiD
"""

import numpy as np

def cost(w, x, y):
  pass

  def gradJ(w):
    pass

  def step_func(x):
    y = x>0
def step_func(y):
    return 2*y.astype(int)-1

print(step_func(np.array([-1.2,0.3])))